(()=>{
"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money={format:n=>`A$${Number(n||0).toFixed(2)}`};
const ACCOUNT="metriaRecoverAccountV1",SESSION="metriaRecoverSessionV1",REPORT="metriaRecoverReportV1",WALLET="metriaRecoverWalletV1";const files=[];let report=null,unlocked=false,installPrompt=null,graphState=null;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const digest=async text=>{const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return[...new Uint8Array(b)].map(v=>v.toString(16).padStart(2,"0")).join("")};
async function createAccount(){const email=$("#authEmail").value.trim().toLowerCase(),pass=$("#authPassword").value;if(!/^\S+@\S+\.\S+$/.test(email))return msg("Enter a valid email address.");if(pass.length<8)return msg("Use at least 8 characters.");const old=JSON.parse(localStorage.getItem(ACCOUNT)||"null");if(old&&old.email!==email)return msg("A different device profile already exists.");const salt=crypto.getRandomValues(new Uint32Array(4)).join("-");localStorage.setItem(ACCOUNT,JSON.stringify({email,salt,verifier:await digest(salt+pass),createdAt:new Date().toISOString()}));localStorage.setItem(SESSION,email);openApp(email)}
async function signIn(){const a=JSON.parse(localStorage.getItem(ACCOUNT)||"null"),email=$("#authEmail").value.trim().toLowerCase();if(!a)return msg("No device profile exists yet. Create an account first.");if(a.email!==email||a.verifier!==await digest(a.salt+$("#authPassword").value))return msg("Email or passphrase is incorrect.");localStorage.setItem(SESSION,email);openApp(email)}
const msg=t=>$("#authMessage").textContent=t;function openApp(email=""){$("#authGate").hidden=true;$("#receiptEmail").value=email;$("#signOut").classList.add("show");const saved=JSON.parse(localStorage.getItem(REPORT)||"null");if(saved){report=saved;renderReport()}}
$("#createAccount").onclick=createAccount;$("#signIn").onclick=signIn;$("#continueDemo").onclick=()=>{unlocked=true;openApp()};$("#signOut").onclick=()=>{localStorage.removeItem(SESSION);location.reload()};const account=JSON.parse(localStorage.getItem(ACCOUNT)||"null");if(account&&localStorage.getItem(SESSION)===account.email)openApp(account.email);

const drop=$("#dropZone"),input=$("#files");$("#chooseFiles").onclick=()=>input.click();input.onchange=e=>addFiles([...e.target.files]);["dragenter","dragover"].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add("drag")}));["dragleave","drop"].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove("drag")}));drop.ondrop=e=>addFiles([...e.dataTransfer.files]);
function addFiles(list){for(const f of list)if(!files.some(x=>x.name===f.name&&x.size===f.size))files.push(f);renderFiles()}
function renderFiles(){$("#fileList").innerHTML=files.map((f,i)=>`<div class="file-row"><span>${escape(f.name)}</span><span>${f.size<1024?f.size+" B":(f.size/1024).toFixed(1)+" KB"} <button class="text-button" data-rm="${i}">Remove</button></span></div>`).join("");$$('[data-rm]').forEach(b=>b.onclick=()=>{files.splice(+b.dataset.rm,1);renderFiles()});$("#scanButton").disabled=!files.length}
function parseCSV(text){const rows=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&q&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')q=!q;else if(c===','&&!q){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);if(rows.length<2)return[];const head=rows.shift().map(x=>x.trim().toLowerCase());return rows.map((r,i)=>{const o={};head.forEach((h,j)=>o[h]=r[j]?.trim()||"");return normalize(o,i)}).filter(Boolean)}
function field(o,names){for(const n of names){const k=Object.keys(o).find(x=>x===n||x.includes(n));if(k&&o[k]!=="")return o[k]}return""}const amount=v=>Math.abs(Number(String(v).replace(/[^0-9.-]/g,"")))||0;
function normalize(o,i){const a=amount(field(o,["debit","amount","value","charge"]));if(!a)return null;const d=new Date(field(o,["date","transaction date","posted","created"])),merchant=field(o,["merchant","description","details","narrative","payee","name"])||"Unlabelled transaction";return{id:`tx-${i}-${Math.random().toString(36).slice(2,6)}`,date:Number.isNaN(+d)?new Date():d,merchant:merchant.replace(/\s+/g," ").trim(),amount:a,source:"Transaction record"}}
function parseText(text){const out=[],dateRe=/(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|\d{4}-\d{2}-\d{2})/,cash=/(?:A?\$\s?)(\d+(?:,\d{3})*(?:\.\d{2})?)/g;for(const [i,line]of text.split(/\n+/).entries()){const vals=[...line.matchAll(cash)];if(!vals.length)continue;const dm=line.match(dateRe),d=dm?new Date(dm[1]):new Date();out.push({id:`doc-${i}-${Math.random().toString(36).slice(2,6)}`,date:Number.isNaN(+d)?new Date():d,merchant:line.replace(dateRe,"").replace(cash,"").replace(/[|,]/g," ").replace(/\s+/g," ").trim().slice(0,90)||"Document line item",amount:amount(vals.at(-1)[1]),source:"Document text"})}return out}
async function pdfText(file){const p=await import("https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs");p.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs";const pdf=await p.getDocument({data:await file.arrayBuffer()}).promise;let text="";for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),c=await page.getTextContent();text+=c.items.map(x=>x.str).join(" ")+"\n"}return text}
async function readEvidence(){const transactions=[],documents=[];for(const file of files){const text=file.name.toLowerCase().endsWith(".pdf")?await pdfText(file):await file.text();documents.push({name:file.name,text});if(/\.csv$/i.test(file.name))transactions.push(...parseCSV(text));else if(/\.json$/i.test(file.name)){try{const j=JSON.parse(text),rows=Array.isArray(j)?j:j.transactions||[];transactions.push(...rows.map(normalize).filter(Boolean))}catch{transactions.push(...parseText(text))}}else transactions.push(...parseText(text))}return{transactions,documents}}
const merchant=s=>s.toLowerCase().replace(/\b(pos|visa|debit|credit|payment|purchase|pty|ltd|australia|au)\b/g,"").replace(/[^a-z0-9]/g,"").slice(0,38);
const finding=(type,title,value,confidence,evidence,reason,next)=>({id:Math.random().toString(36).slice(2),type,title,value:+value.toFixed(2),confidence,evidence,reason,next});
function detect(data){const tx=[...data.transactions].sort((a,b)=>a.date-b.date),groups={};tx.forEach(t=>(groups[merchant(t.merchant)]??=[]).push(t));const found=[];for(const [key,items]of Object.entries(groups)){if(!key||items.length<2)continue;for(let i=1;i<items.length;i++){const a=items[i-1],b=items[i],hours=Math.abs(b.date-a.date)/36e5;if(Math.abs(a.amount-b.amount)<.01&&hours<=72)found.push(finding("duplicate","Possible duplicate charge",b.amount,.92,[a,b],"Matching charges from the same merchant occurred within 72 hours.","Ask the merchant to confirm whether both charges map to separate purchases."))}if(items.length>=3){const base=items.slice(0,-1).reduce((s,x)=>s+x.amount,0)/(items.length-1),last=items.at(-1);if(base&&last.amount>base*1.12)found.push(finding("fee-drift","Recurring fee increase",last.amount-base,.66,items.slice(-3),`Latest charge is ${Math.round((last.amount/base-1)*100)}% above its earlier recurring level.`,"Check the active plan notice and contract version."))}}
 for(const doc of data.documents){for(const line of doc.text.split(/\n+/)){if(!/(?:cancelled|canceled|cancellation|terminated)/i.test(line))continue;const dm=line.match(/(\d{1,2}[\/-]\d{1,2}[\/-]\d{2,4}|\d{4}-\d{2}-\d{2})/);if(!dm)continue;const parts=dm[1].split(/[\/-]/).map(Number),d=parts[0]>31?new Date(parts[0],parts[1]-1,parts[2]):new Date(parts[2]<100?2000+parts[2]:parts[2],parts[1]-1,parts[0]);if(Number.isNaN(+d))continue;const words=line.toLowerCase().split(/\W+/).filter(w=>w.length>2&&!/cancel|termin|date|confirm|membership/.test(w));for(const t of tx.filter(x=>x.date>d))if(words.some(w=>t.merchant.toLowerCase().includes(w)))found.push(finding("post-cancel","Charge after cancellation",t.amount,.88,[t],`Charge appears after a cancellation reference dated ${d.toLocaleDateString("en-AU")}.`,"Attach the cancellation confirmation and request reversal."))}}
 const all=data.documents.map(d=>d.text).join("\n").toLowerCase(),outages=[...all.matchAll(/(?:outage|service unavailable|no service)[^\n]{0,45}?(\d+(?:\.\d+)?)\s*(?:hours?|hrs?)/g)].map(x=>+x[1]),bill=tx.filter(t=>/telstra|optus|vodafone|internet|broadband|nbn|telecom|harbournet/i.test(t.merchant)).at(-1);if(outages.length&&bill)found.push(finding("service-credit","Service-credit review",bill.amount/30/24*Math.max(...outages),.58,[bill],`Documents mention ${Math.max(...outages)} hours without service; value prorates the latest relevant monthly charge.`,"Confirm the provider SLA and whether a credit was already applied."));
 const uniq=new Map();for(const f of found){const k=f.type+f.evidence.map(e=>e.id).join("|");if(!uniq.has(k))uniq.set(k,f)}return[...uniq.values()].sort((a,b)=>b.confidence-a.confidence)}
function build(data,findings){return{createdAt:new Date().toISOString(),transactions:data.transactions,documents:data.documents.map(d=>d.name),findings,total:+findings.reduce((s,f)=>s+f.value,0).toFixed(2),coverage:findings.length?Math.round(findings.reduce((s,f)=>s+f.confidence,0)/findings.length*100):0}}
$("#demoButton").onclick=()=>{const csv=`Date,Description,Amount\n2026-07-02,HarbourNet Broadband,89.00\n2026-07-19,Cloudbox Pro,24.95\n2026-07-19,Cloudbox Pro,24.95\n2026-08-02,HarbourNet Broadband,89.00\n2026-08-08,Metro Gym,30.00\n2026-08-22,Streamly,19.99\n2026-09-02,HarbourNet Broadband,99.00\n2026-09-08,Metro Gym,30.00`,note=`Metro Gym membership cancellation confirmed 01/08/2026.\nHarbourNet service unavailable for 8 hours on 18/08/2026.`;files.splice(0,files.length,new File([csv],"illustrative-transactions.csv",{type:"text/csv"}),new File([note],"illustrative-service-notes.txt",{type:"text/plain"}));renderFiles();scan()};
$("#scanButton").onclick=scan;async function scan(){if(!files.length)return;const status=$("#scanStatus"),bar=$("#scanProgress"),label=$("#scanLabel");status.classList.add("active");$("#scanButton").disabled=true;try{for(const [p,t]of[[12,"Reading records…"],[35,"Normalizing transactions…"],[60,"Detecting temporal invariants…"],[80,"Embedding evidence paths…"],[95,"Quantifying candidate value…"]]){bar.style.width=p+"%";label.textContent=t;await new Promise(r=>setTimeout(r,180))}const data=await readEvidence(),found=detect(data);report=build(data,found);localStorage.setItem(REPORT,JSON.stringify(report));bar.style.width="100%";label.textContent=`Mapped ${data.transactions.length} transactions into your recovery twin.`;renderReport()}catch(e){console.error(e);label.textContent="This file could not be parsed. Try a CSV export or text-searchable PDF."}finally{$("#scanButton").disabled=false}}
function renderReport(){$("#emptyState").hidden=true;$("#results").hidden=false;$("#graphCard").hidden=false;$("#recoveryWallet").hidden=false;$("#totalValue").textContent=money.format(report.total);$("#candidateCount").textContent=report.findings.length;$("#coverage").textContent=report.coverage+"%";$("#previewHeadline").textContent=report.findings.length?`${money.format(report.total)} in potential value detected`:"No strong candidates in these records";$("#findings").innerHTML=report.findings.length?report.findings.map((f,i)=>`<article class="finding ${unlocked?'':'locked'}"><div class="finding-head"><h3>${escape(f.title)}</h3><span class="tag">${Math.round(f.confidence*100)}% evidence match</span></div><div class="sensitive"><p><b>${money.format(f.value)}</b> · ${escape(f.evidence[0]?.merchant||"Document evidence")}</p><p>${escape(f.reason)}</p><p><b>Next action:</b> ${escape(f.next)}</p></div><div class="lock-cover">Candidate ${i+1} · unlock the evidence path</div></article>`).join(""):`<article class="finding"><h3>No high-signal discrepancies found</h3><p>Add more months or contract documents to improve coverage.</p></article>`;$("#graphTransactions").textContent=`${report.transactions.length} transactions`;$("#graphEvidence").textContent=`${report.findings.length*4+1} evidence nodes`;$("#graphValue").textContent=`${money.format(report.total)} mapped value`;renderWallet();drawGraph()}

function wallet(){return JSON.parse(localStorage.getItem(WALLET)||'{"confirmed":0,"paid":0,"events":[]}')}function saveWallet(w){localStorage.setItem(WALLET,JSON.stringify(w));renderWallet()}function renderWallet(){if(!report)return;const w=wallet();$("#potentialBalance").textContent=money.format(report.total);$("#confirmedBalance").textContent=money.format(w.confirmed);$("#paidBalance").textContent=money.format(w.paid);$("#availableBalance").textContent=money.format(Math.max(0,w.confirmed-w.paid))}
$("#prepareRecovery").onclick=()=>{if(!report?.findings.length){$("#walletStatus").textContent="Run a scan with at least one candidate first.";return}if(!unlocked){checkout("scan");$("#walletStatus").textContent="Unlock the evidence report before generating provider-specific recovery requests.";return}$("#payoutModal").hidden=false};
$("#recordPayment").onclick=()=>{const raw=prompt("Enter the refund amount already received from the provider (AUD):"),value=Number(String(raw||"").replace(/[^0-9.]/g,""));if(!value||value<=0)return;const w=wallet();w.paid=+(w.paid+value).toFixed(2);w.confirmed=Math.max(w.confirmed,w.paid);w.events.push({type:"refund received",amount:value,date:new Date().toISOString()});saveWallet(w);$("#walletStatus").textContent=`Recorded ${money.format(value)} paid directly to you.`};
$("#closePayout").onclick=()=>$("#payoutModal").hidden=true;$("#payoutMethod").onchange=e=>$("#bankFields").hidden=e.target.value!=="bank";
$("#downloadInstruction").onclick=()=>{const bank=$("#payoutMethod").value==="bank",name=$("#payoutName").value.trim(),bsb=$("#payoutBsb").value.replace(/\D/g,""),number=$("#payoutAccount").value.replace(/\D/g,"");if(bank&&(!name||bsb.length!==6||number.length<5)){$("#payoutMessage").textContent="Enter an account name, six-digit BSB and valid account number.";return}const evidence=report.findings.map((f,i)=>`${i+1}. ${f.title}\n   Amount requested: ${money.format(f.value)}\n   Evidence: ${f.reason}\n   Requested action: ${f.next}`).join("\n\n"),destination=bank?`Please pay by bank transfer to:\nAccount name: ${name}\nBSB: ${bsb.slice(0,3)}-${bsb.slice(3)}\nAccount number: ${number}`:"Please return the approved refund to the original payment method used for the disputed transaction(s).";const text=`METRIA RECOVERY REQUEST\nGenerated: ${new Date().toLocaleString("en-AU")}\n\nI request review and direct refund of the following transaction discrepancies. I confirm that the factual statements and attached records should be verified against your records.\n\n${evidence}\n\nTOTAL POTENTIAL REFUND: ${money.format(report.total)}\n\nPAYOUT INSTRUCTION\n${destination}\n\nPlease confirm the approved amount and expected payment date in writing. This document is a consumer-generated request and is not legal advice.`;const blob=new Blob([text],{type:"text/plain"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`metria-recovery-request-${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$("#payoutMessage").textContent="Instruction generated locally. Review it before sending it to the provider."};
function graphNodes(){const nodes=[{id:"root",label:"Your financial exhaust",kind:"root",r:0,a:0,color:"#9cf3c2",size:10,detail:`${report.transactions.length} imported transactions`}];report.findings.forEach((f,i)=>{const a=i/Math.max(1,report.findings.length)*Math.PI*2;const tx=f.evidence[0];nodes.push({id:`tx${i}`,label:tx.merchant,kind:"transaction",r:.31,a,color:"#5cd5f7",size:7,parent:"root",detail:`${money.format(tx.amount)} on ${new Date(tx.date).toLocaleDateString("en-AU")}`},{id:`an${i}`,label:f.title,kind:"invariant",r:.57,a:a+.13,color:"#ffc875",size:7,parent:`tx${i}`,detail:f.reason},{id:`rule${i}`,label:"Evidence test",kind:"rule",r:.76,a:a+.23,color:"#cfa8ff",size:6,parent:`an${i}`,detail:`${Math.round(f.confidence*100)}% evidence match · requires provider/contract verification`},{id:`act${i}`,label:`Recover ${money.format(f.value)}`,kind:"action",r:.92,a:a+.33,color:"#ff7f76",size:8,parent:`rule${i}`,detail:f.next})});return nodes}
function drawGraph(){const canvas=$("#evidenceGraph"),ctx=canvas.getContext("2d"),nodes=graphNodes();graphState={canvas,ctx,nodes,rotation:0,points:[]};const paint=()=>{const {rotation}=graphState,d=Math.min(devicePixelRatio||1,2),w=canvas.clientWidth,h=canvas.clientHeight,cx=w/2,cy=h/2,R=Math.min(w,h)*.42;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);ctx.strokeStyle="#294456";ctx.lineWidth=1;for(const r of[.25,.5,.75,1]){ctx.beginPath();ctx.arc(cx,cy,R*r,0,7);ctx.stroke()}const pt=n=>({x:cx+Math.cos(n.a+rotation)*R*n.r,y:cy+Math.sin(n.a+rotation)*R*n.r});const map=new Map(nodes.map(n=>[n.id,n]));for(const n of nodes)if(n.parent){const a=pt(map.get(n.parent)),b=pt(n);ctx.strokeStyle="#4b718899";ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.quadraticCurveTo(cx,cy,b.x,b.y);ctx.stroke()}graphState.points=nodes.map(n=>({...n,...pt(n)}));for(const n of graphState.points){ctx.fillStyle=n.color;ctx.shadowColor=n.color;ctx.shadowBlur=15;ctx.beginPath();ctx.arc(n.x,n.y,n.size,0,7);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#dfeaf0";ctx.font="11px system-ui";ctx.fillText(n.label.slice(0,26),n.x+10,n.y+4)}};paint();let start=null;canvas.onpointerdown=e=>{start=e.clientX;canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(start==null)return;graphState.rotation+=(e.clientX-start)*.008;start=e.clientX;paint()};canvas.onpointerup=e=>{start=null;canvas.releasePointerCapture(e.pointerId);const rect=canvas.getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top,n=graphState.points.find(p=>(p.x-x)**2+(p.y-y)**2<(p.size+12)**2);if(n)$("#nodePanel").innerHTML=`<b style="color:${n.color}">${escape(n.label)}</b><br>${escape(n.detail)}`};addEventListener("resize",paint,{once:true})}
function checkout(kind="scan"){const monitor=kind==="monitor";$("#checkoutTitle").textContent=monitor?"Start continuous monitoring":"Unlock the full scan";$("#checkoutProduct").textContent=monitor?"Continuous monitoring":"Full evidence report";$("#checkoutPrice").textContent=monitor?"A$12 / month":"A$9.90";$("#checkoutDescription").textContent=monitor?"Keep checking new records and maintain a recovery timeline.":"Reveal exact transactions, calculations and draft actions.";$("#checkoutModal").hidden=false;$("#checkoutContinue").dataset.product=monitor?"monitor":"scan"}
$("#unlockButton").onclick=()=>checkout();$$('[data-checkout]').forEach(b=>b.onclick=()=>checkout(b.dataset.checkout));$("#closeCheckout").onclick=()=>$("#checkoutModal").hidden=true;$("#checkoutContinue").onclick=()=>{const url=window.METRIA_CHECKOUT_URLS?.[$("#checkoutContinue").dataset.product];if(url)return location.href=url;$("#checkoutMessage").textContent="The product is operational; merchant checkout activation requires the owner’s payment-provider link. No card data was collected."};
addEventListener("beforeinstallprompt",e=>{e.preventDefault();installPrompt=e;$("#install").style.display="inline-block"});$("#install").onclick=async()=>{if(installPrompt){await installPrompt.prompt();installPrompt=null;$("#install").style.display="none"}else alert("Use Add to Home Screen in your browser menu.")};if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js",{updateViaCache:"none"}).then(r=>r.update()).catch(()=>{});
})();
